timezone: Europe/Madrid
title: NaosInfoSec
tagline: Technology and Ethical hacking blog.  # it will display as the sub-title
description: Ethical hacking blog.
url: 'https://naosinfosec.com'
github:
  username: raiabril
# paginate: 10
permalink: /:categories/:slug
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:   # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: highlight
    default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

